coverage:
  paths:
    - coverage.out
codeToTestRatio:
  code:
    - './api/**/*.go'
    - '!/api/**/*_test.go'
  test:
    - './api/**/*_test.go'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}