version: "3.9"
services:
  api:
    container_name: tunetrail-api
    hostname: tunetrail-api
    build:
      context: .
      target: dev
      dockerfile: ./api/Dockerfile
    environment:
      TUNETRAIL_ENV: dev
      PORT: 8080
      TUNETRAIL_DB_HOST: tunetrail-db
      TUNETRAIL_DB_PORT: 5432
      TUNETRAIL_DB_USER: tunetrail
      TUNETRAIL_DB_PASSWORD: tunetrail
      TUNETRAIL_DB_NAME: tunetrail
    volumes:
      # .gitを含むルートディレクトリを指定する
      - .:/workspace:cached
    ports:
      - "18000:8080"
    networks:
      - tunetrail-internal
      - tunetrail-external
    command: sleep infinity

  db:
    container_name: tunetrail-db
    hostname: tunetrail-db
    image: postgres:15.2
    platform: linux/amd64
    environment:
      POSTGRES_USER: tunetrail
      POSTGRES_PASSWORD: tunetrail
      POSTGRES_DB: tunetrail
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # dockerコンテナ起動時に自動で実行される.sqlファイル
      - ./api/_tools/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5555:5432"
    networks:
      - tunetrail-internal

  frontend:
    container_name: tunetrail-frontend
    hostname: tunetrail-frontend
    build:
      context: .
      target: dev
      dockerfile: ./frontend/Dockerfile
    environment:
      TODO_ENV: dev
      TODO_API_HOST: tunetrail-api
      TODO_API_PORT: 8080
    tty: true
    volumes:
      # .gitを含むルートディレクトリを指定する
      - .:/workspace:cached
    ports:
      - '3000:3000'
    networks:
      - tunetrail-external

networks:
  # 内部ネットワーク
  tunetrail-internal:
    driver: bridge
    internal: true
  # 公開ネットワーク
  tunetrail-external:
    driver: bridge
    external: true

volumes:
  postgres-data:
