version: "3.9"

services:
  reverse-proxy:
    container_name: tunetrail-reverse-proxy
    hostname: tunetrail-reverse-proxy
    build:
      context: .
      target: dev
      dockerfile: ./reverse-proxy-for-dev/Dockerfile
    volumes:
      # .gitを含むルートディレクトリを指定する
      - .:/workspace:cached
    ports:
      - "1443:443"
      - "3000:444"

  webapp:
    container_name: tunetrail-webapp
    hostname: tunetrail-webapp
    build:
      context: .
      target: dev
      dockerfile: ./webapp/Dockerfile
    tty: true
    volumes:
      # .gitを含むルートディレクトリを指定する
      - .:/workspace:cached

  restapi:
    container_name: tunetrail-restapi
    hostname: tunetrail-restapi
    build:
      context: .
      target: dev
      dockerfile: ./restapi/Dockerfile
    env_file:
      - ./restapi/.env
    volumes:
      # .gitを含むルートディレクトリを指定する
      - .:/workspace:cached

  db:
    container_name: tunetrail-db
    hostname: tunetrail-db
    image: postgres:15.2
    platform: linux/amd64
    environment:
      POSTGRES_USER: tunetrail
      POSTGRES_PASSWORD: tunetrail
      POSTGRES_DB: tunetrail
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # dockerコンテナ起動時に自動で実行される.sqlファイル
      - ./migration/_tools/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./migration/_tools/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5555:5432"
    # 設定ファイルを読み込む
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  migration:
    container_name: tunetrail-migration
    hostname: tunetrail-migration
    build:
      context: .
      target: dev
      dockerfile: ./migration/Dockerfile
    environment:
      ENV: dev
      TUNETRAIL_DB_HOST: tunetrail-db
      TUNETRAIL_DB_PORT: 5432
      TUNETRAIL_DB_USER: tunetrail
      TUNETRAIL_DB_PASSWORD: tunetrail
      TUNETRAIL_DB_NAME: tunetrail
      DRY_RUN: true
    volumes:
      # .gitを含むルートディレクトリを指定する
      - .:/workspace:cached
    ports:
      - "18009:8080"

volumes:
  postgres-data:
