// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"database/sql"
	"github.com/jmoiron/sqlx"
	"sync"
)

// BeginnerMock is a mock implementation of store.Beginner.
//
//	func TestSomethingThatUsesBeginner(t *testing.T) {
//
//		// make and configure a mocked store.Beginner
//		mockedBeginner := &BeginnerMock{
//			BeginTxxFunc: func(ctx context.Context, opts *sql.TxOptions) (*sqlx.Tx, error) {
//				panic("mock out the BeginTxx method")
//			},
//		}
//
//		// use mockedBeginner in code that requires store.Beginner
//		// and then make assertions.
//
//	}
type BeginnerMock struct {
	// BeginTxxFunc mocks the BeginTxx method.
	BeginTxxFunc func(ctx context.Context, opts *sql.TxOptions) (*sqlx.Tx, error)

	// calls tracks calls to the methods.
	calls struct {
		// BeginTxx holds details about calls to the BeginTxx method.
		BeginTxx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts *sql.TxOptions
		}
	}
	lockBeginTxx sync.RWMutex
}

// BeginTxx calls BeginTxxFunc.
func (mock *BeginnerMock) BeginTxx(ctx context.Context, opts *sql.TxOptions) (*sqlx.Tx, error) {
	if mock.BeginTxxFunc == nil {
		panic("BeginnerMock.BeginTxxFunc: method is nil but Beginner.BeginTxx was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts *sql.TxOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockBeginTxx.Lock()
	mock.calls.BeginTxx = append(mock.calls.BeginTxx, callInfo)
	mock.lockBeginTxx.Unlock()
	return mock.BeginTxxFunc(ctx, opts)
}

// BeginTxxCalls gets all the calls that were made to BeginTxx.
// Check the length with:
//
//	len(mockedBeginner.BeginTxxCalls())
func (mock *BeginnerMock) BeginTxxCalls() []struct {
	Ctx  context.Context
	Opts *sql.TxOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts *sql.TxOptions
	}
	mock.lockBeginTxx.RLock()
	calls = mock.calls.BeginTxx
	mock.lockBeginTxx.RUnlock()
	return calls
}

// PreparerMock is a mock implementation of store.Preparer.
//
//	func TestSomethingThatUsesPreparer(t *testing.T) {
//
//		// make and configure a mocked store.Preparer
//		mockedPreparer := &PreparerMock{
//			PreparexContextFunc: func(ctx context.Context, query string) (*sqlx.Stmt, error) {
//				panic("mock out the PreparexContext method")
//			},
//		}
//
//		// use mockedPreparer in code that requires store.Preparer
//		// and then make assertions.
//
//	}
type PreparerMock struct {
	// PreparexContextFunc mocks the PreparexContext method.
	PreparexContextFunc func(ctx context.Context, query string) (*sqlx.Stmt, error)

	// calls tracks calls to the methods.
	calls struct {
		// PreparexContext holds details about calls to the PreparexContext method.
		PreparexContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
		}
	}
	lockPreparexContext sync.RWMutex
}

// PreparexContext calls PreparexContextFunc.
func (mock *PreparerMock) PreparexContext(ctx context.Context, query string) (*sqlx.Stmt, error) {
	if mock.PreparexContextFunc == nil {
		panic("PreparerMock.PreparexContextFunc: method is nil but Preparer.PreparexContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockPreparexContext.Lock()
	mock.calls.PreparexContext = append(mock.calls.PreparexContext, callInfo)
	mock.lockPreparexContext.Unlock()
	return mock.PreparexContextFunc(ctx, query)
}

// PreparexContextCalls gets all the calls that were made to PreparexContext.
// Check the length with:
//
//	len(mockedPreparer.PreparexContextCalls())
func (mock *PreparerMock) PreparexContextCalls() []struct {
	Ctx   context.Context
	Query string
} {
	var calls []struct {
		Ctx   context.Context
		Query string
	}
	mock.lockPreparexContext.RLock()
	calls = mock.calls.PreparexContext
	mock.lockPreparexContext.RUnlock()
	return calls
}

// QueryerMock is a mock implementation of store.Queryer.
//
//	func TestSomethingThatUsesQueryer(t *testing.T) {
//
//		// make and configure a mocked store.Queryer
//		mockedQueryer := &QueryerMock{
//			ExecContextFunc: func(ctx context.Context, query string, args ...any) (sql.Result, error) {
//				panic("mock out the ExecContext method")
//			},
//			GetContextFunc: func(ctx context.Context, dest interface{}, query string, args ...any) error {
//				panic("mock out the GetContext method")
//			},
//			NamedExecContextFunc: func(ctx context.Context, query string, arg interface{}) (sql.Result, error) {
//				panic("mock out the NamedExecContext method")
//			},
//			PreparexContextFunc: func(ctx context.Context, query string) (*sqlx.Stmt, error) {
//				panic("mock out the PreparexContext method")
//			},
//			QueryRowxContextFunc: func(ctx context.Context, query string, args ...any) *sqlx.Row {
//				panic("mock out the QueryRowxContext method")
//			},
//			QueryxContextFunc: func(ctx context.Context, query string, args ...any) (*sqlx.Rows, error) {
//				panic("mock out the QueryxContext method")
//			},
//			SelectContextFunc: func(ctx context.Context, dest interface{}, query string, args ...any) error {
//				panic("mock out the SelectContext method")
//			},
//		}
//
//		// use mockedQueryer in code that requires store.Queryer
//		// and then make assertions.
//
//	}
type QueryerMock struct {
	// ExecContextFunc mocks the ExecContext method.
	ExecContextFunc func(ctx context.Context, query string, args ...any) (sql.Result, error)

	// GetContextFunc mocks the GetContext method.
	GetContextFunc func(ctx context.Context, dest interface{}, query string, args ...any) error

	// NamedExecContextFunc mocks the NamedExecContext method.
	NamedExecContextFunc func(ctx context.Context, query string, arg interface{}) (sql.Result, error)

	// PreparexContextFunc mocks the PreparexContext method.
	PreparexContextFunc func(ctx context.Context, query string) (*sqlx.Stmt, error)

	// QueryRowxContextFunc mocks the QueryRowxContext method.
	QueryRowxContextFunc func(ctx context.Context, query string, args ...any) *sqlx.Row

	// QueryxContextFunc mocks the QueryxContext method.
	QueryxContextFunc func(ctx context.Context, query string, args ...any) (*sqlx.Rows, error)

	// SelectContextFunc mocks the SelectContext method.
	SelectContextFunc func(ctx context.Context, dest interface{}, query string, args ...any) error

	// calls tracks calls to the methods.
	calls struct {
		// ExecContext holds details about calls to the ExecContext method.
		ExecContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
		// GetContext holds details about calls to the GetContext method.
		GetContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dest is the dest argument value.
			Dest interface{}
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
		// NamedExecContext holds details about calls to the NamedExecContext method.
		NamedExecContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Arg is the arg argument value.
			Arg interface{}
		}
		// PreparexContext holds details about calls to the PreparexContext method.
		PreparexContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
		}
		// QueryRowxContext holds details about calls to the QueryRowxContext method.
		QueryRowxContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
		// QueryxContext holds details about calls to the QueryxContext method.
		QueryxContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
		// SelectContext holds details about calls to the SelectContext method.
		SelectContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dest is the dest argument value.
			Dest interface{}
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
	}
	lockExecContext      sync.RWMutex
	lockGetContext       sync.RWMutex
	lockNamedExecContext sync.RWMutex
	lockPreparexContext  sync.RWMutex
	lockQueryRowxContext sync.RWMutex
	lockQueryxContext    sync.RWMutex
	lockSelectContext    sync.RWMutex
}

// ExecContext calls ExecContextFunc.
func (mock *QueryerMock) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	if mock.ExecContextFunc == nil {
		panic("QueryerMock.ExecContextFunc: method is nil but Queryer.ExecContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockExecContext.Lock()
	mock.calls.ExecContext = append(mock.calls.ExecContext, callInfo)
	mock.lockExecContext.Unlock()
	return mock.ExecContextFunc(ctx, query, args...)
}

// ExecContextCalls gets all the calls that were made to ExecContext.
// Check the length with:
//
//	len(mockedQueryer.ExecContextCalls())
func (mock *QueryerMock) ExecContextCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockExecContext.RLock()
	calls = mock.calls.ExecContext
	mock.lockExecContext.RUnlock()
	return calls
}

// GetContext calls GetContextFunc.
func (mock *QueryerMock) GetContext(ctx context.Context, dest interface{}, query string, args ...any) error {
	if mock.GetContextFunc == nil {
		panic("QueryerMock.GetContextFunc: method is nil but Queryer.GetContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Dest  interface{}
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Dest:  dest,
		Query: query,
		Args:  args,
	}
	mock.lockGetContext.Lock()
	mock.calls.GetContext = append(mock.calls.GetContext, callInfo)
	mock.lockGetContext.Unlock()
	return mock.GetContextFunc(ctx, dest, query, args...)
}

// GetContextCalls gets all the calls that were made to GetContext.
// Check the length with:
//
//	len(mockedQueryer.GetContextCalls())
func (mock *QueryerMock) GetContextCalls() []struct {
	Ctx   context.Context
	Dest  interface{}
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Dest  interface{}
		Query string
		Args  []any
	}
	mock.lockGetContext.RLock()
	calls = mock.calls.GetContext
	mock.lockGetContext.RUnlock()
	return calls
}

// NamedExecContext calls NamedExecContextFunc.
func (mock *QueryerMock) NamedExecContext(ctx context.Context, query string, arg interface{}) (sql.Result, error) {
	if mock.NamedExecContextFunc == nil {
		panic("QueryerMock.NamedExecContextFunc: method is nil but Queryer.NamedExecContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Arg   interface{}
	}{
		Ctx:   ctx,
		Query: query,
		Arg:   arg,
	}
	mock.lockNamedExecContext.Lock()
	mock.calls.NamedExecContext = append(mock.calls.NamedExecContext, callInfo)
	mock.lockNamedExecContext.Unlock()
	return mock.NamedExecContextFunc(ctx, query, arg)
}

// NamedExecContextCalls gets all the calls that were made to NamedExecContext.
// Check the length with:
//
//	len(mockedQueryer.NamedExecContextCalls())
func (mock *QueryerMock) NamedExecContextCalls() []struct {
	Ctx   context.Context
	Query string
	Arg   interface{}
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Arg   interface{}
	}
	mock.lockNamedExecContext.RLock()
	calls = mock.calls.NamedExecContext
	mock.lockNamedExecContext.RUnlock()
	return calls
}

// PreparexContext calls PreparexContextFunc.
func (mock *QueryerMock) PreparexContext(ctx context.Context, query string) (*sqlx.Stmt, error) {
	if mock.PreparexContextFunc == nil {
		panic("QueryerMock.PreparexContextFunc: method is nil but Queryer.PreparexContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockPreparexContext.Lock()
	mock.calls.PreparexContext = append(mock.calls.PreparexContext, callInfo)
	mock.lockPreparexContext.Unlock()
	return mock.PreparexContextFunc(ctx, query)
}

// PreparexContextCalls gets all the calls that were made to PreparexContext.
// Check the length with:
//
//	len(mockedQueryer.PreparexContextCalls())
func (mock *QueryerMock) PreparexContextCalls() []struct {
	Ctx   context.Context
	Query string
} {
	var calls []struct {
		Ctx   context.Context
		Query string
	}
	mock.lockPreparexContext.RLock()
	calls = mock.calls.PreparexContext
	mock.lockPreparexContext.RUnlock()
	return calls
}

// QueryRowxContext calls QueryRowxContextFunc.
func (mock *QueryerMock) QueryRowxContext(ctx context.Context, query string, args ...any) *sqlx.Row {
	if mock.QueryRowxContextFunc == nil {
		panic("QueryerMock.QueryRowxContextFunc: method is nil but Queryer.QueryRowxContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockQueryRowxContext.Lock()
	mock.calls.QueryRowxContext = append(mock.calls.QueryRowxContext, callInfo)
	mock.lockQueryRowxContext.Unlock()
	return mock.QueryRowxContextFunc(ctx, query, args...)
}

// QueryRowxContextCalls gets all the calls that were made to QueryRowxContext.
// Check the length with:
//
//	len(mockedQueryer.QueryRowxContextCalls())
func (mock *QueryerMock) QueryRowxContextCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockQueryRowxContext.RLock()
	calls = mock.calls.QueryRowxContext
	mock.lockQueryRowxContext.RUnlock()
	return calls
}

// QueryxContext calls QueryxContextFunc.
func (mock *QueryerMock) QueryxContext(ctx context.Context, query string, args ...any) (*sqlx.Rows, error) {
	if mock.QueryxContextFunc == nil {
		panic("QueryerMock.QueryxContextFunc: method is nil but Queryer.QueryxContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockQueryxContext.Lock()
	mock.calls.QueryxContext = append(mock.calls.QueryxContext, callInfo)
	mock.lockQueryxContext.Unlock()
	return mock.QueryxContextFunc(ctx, query, args...)
}

// QueryxContextCalls gets all the calls that were made to QueryxContext.
// Check the length with:
//
//	len(mockedQueryer.QueryxContextCalls())
func (mock *QueryerMock) QueryxContextCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockQueryxContext.RLock()
	calls = mock.calls.QueryxContext
	mock.lockQueryxContext.RUnlock()
	return calls
}

// SelectContext calls SelectContextFunc.
func (mock *QueryerMock) SelectContext(ctx context.Context, dest interface{}, query string, args ...any) error {
	if mock.SelectContextFunc == nil {
		panic("QueryerMock.SelectContextFunc: method is nil but Queryer.SelectContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Dest  interface{}
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Dest:  dest,
		Query: query,
		Args:  args,
	}
	mock.lockSelectContext.Lock()
	mock.calls.SelectContext = append(mock.calls.SelectContext, callInfo)
	mock.lockSelectContext.Unlock()
	return mock.SelectContextFunc(ctx, dest, query, args...)
}

// SelectContextCalls gets all the calls that were made to SelectContext.
// Check the length with:
//
//	len(mockedQueryer.SelectContextCalls())
func (mock *QueryerMock) SelectContextCalls() []struct {
	Ctx   context.Context
	Dest  interface{}
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Dest  interface{}
		Query string
		Args  []any
	}
	mock.lockSelectContext.RLock()
	calls = mock.calls.SelectContext
	mock.lockSelectContext.RUnlock()
	return calls
}
