// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/cognitoidentityprovider"
	"sync"
)

// Ensure, that AuthProviderMock does implement AuthProvider.
// If this is not the case, regenerate this file with moq.
var _ AuthProvider = &AuthProviderMock{}

// AuthProviderMock is a mock implementation of AuthProvider.
//
//	func TestSomethingThatUsesAuthProvider(t *testing.T) {
//
//		// make and configure a mocked AuthProvider
//		mockedAuthProvider := &AuthProviderMock{
//			AdminInitiateAuthFunc: func(input *cognitoidentityprovider.AdminInitiateAuthInput) (*cognitoidentityprovider.AdminInitiateAuthOutput, error) {
//				panic("mock out the AdminInitiateAuth method")
//			},
//			ConfirmSignUpWithContextFunc: func(ctx context.Context, input *cognitoidentityprovider.ConfirmSignUpInput, opts ...request.Option) (*cognitoidentityprovider.ConfirmSignUpOutput, error) {
//				panic("mock out the ConfirmSignUpWithContext method")
//			},
//			SignUpWithContextFunc: func(ctx context.Context, input *cognitoidentityprovider.SignUpInput, opts ...request.Option) (*cognitoidentityprovider.SignUpOutput, error) {
//				panic("mock out the SignUpWithContext method")
//			},
//		}
//
//		// use mockedAuthProvider in code that requires AuthProvider
//		// and then make assertions.
//
//	}
type AuthProviderMock struct {
	// AdminInitiateAuthFunc mocks the AdminInitiateAuth method.
	AdminInitiateAuthFunc func(input *cognitoidentityprovider.AdminInitiateAuthInput) (*cognitoidentityprovider.AdminInitiateAuthOutput, error)

	// ConfirmSignUpWithContextFunc mocks the ConfirmSignUpWithContext method.
	ConfirmSignUpWithContextFunc func(ctx context.Context, input *cognitoidentityprovider.ConfirmSignUpInput, opts ...request.Option) (*cognitoidentityprovider.ConfirmSignUpOutput, error)

	// SignUpWithContextFunc mocks the SignUpWithContext method.
	SignUpWithContextFunc func(ctx context.Context, input *cognitoidentityprovider.SignUpInput, opts ...request.Option) (*cognitoidentityprovider.SignUpOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// AdminInitiateAuth holds details about calls to the AdminInitiateAuth method.
		AdminInitiateAuth []struct {
			// Input is the input argument value.
			Input *cognitoidentityprovider.AdminInitiateAuthInput
		}
		// ConfirmSignUpWithContext holds details about calls to the ConfirmSignUpWithContext method.
		ConfirmSignUpWithContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *cognitoidentityprovider.ConfirmSignUpInput
			// Opts is the opts argument value.
			Opts []request.Option
		}
		// SignUpWithContext holds details about calls to the SignUpWithContext method.
		SignUpWithContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *cognitoidentityprovider.SignUpInput
			// Opts is the opts argument value.
			Opts []request.Option
		}
	}
	lockAdminInitiateAuth        sync.RWMutex
	lockConfirmSignUpWithContext sync.RWMutex
	lockSignUpWithContext        sync.RWMutex
}

// AdminInitiateAuth calls AdminInitiateAuthFunc.
func (mock *AuthProviderMock) AdminInitiateAuth(input *cognitoidentityprovider.AdminInitiateAuthInput) (*cognitoidentityprovider.AdminInitiateAuthOutput, error) {
	if mock.AdminInitiateAuthFunc == nil {
		panic("AuthProviderMock.AdminInitiateAuthFunc: method is nil but AuthProvider.AdminInitiateAuth was just called")
	}
	callInfo := struct {
		Input *cognitoidentityprovider.AdminInitiateAuthInput
	}{
		Input: input,
	}
	mock.lockAdminInitiateAuth.Lock()
	mock.calls.AdminInitiateAuth = append(mock.calls.AdminInitiateAuth, callInfo)
	mock.lockAdminInitiateAuth.Unlock()
	return mock.AdminInitiateAuthFunc(input)
}

// AdminInitiateAuthCalls gets all the calls that were made to AdminInitiateAuth.
// Check the length with:
//
//	len(mockedAuthProvider.AdminInitiateAuthCalls())
func (mock *AuthProviderMock) AdminInitiateAuthCalls() []struct {
	Input *cognitoidentityprovider.AdminInitiateAuthInput
} {
	var calls []struct {
		Input *cognitoidentityprovider.AdminInitiateAuthInput
	}
	mock.lockAdminInitiateAuth.RLock()
	calls = mock.calls.AdminInitiateAuth
	mock.lockAdminInitiateAuth.RUnlock()
	return calls
}

// ConfirmSignUpWithContext calls ConfirmSignUpWithContextFunc.
func (mock *AuthProviderMock) ConfirmSignUpWithContext(ctx context.Context, input *cognitoidentityprovider.ConfirmSignUpInput, opts ...request.Option) (*cognitoidentityprovider.ConfirmSignUpOutput, error) {
	if mock.ConfirmSignUpWithContextFunc == nil {
		panic("AuthProviderMock.ConfirmSignUpWithContextFunc: method is nil but AuthProvider.ConfirmSignUpWithContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *cognitoidentityprovider.ConfirmSignUpInput
		Opts  []request.Option
	}{
		Ctx:   ctx,
		Input: input,
		Opts:  opts,
	}
	mock.lockConfirmSignUpWithContext.Lock()
	mock.calls.ConfirmSignUpWithContext = append(mock.calls.ConfirmSignUpWithContext, callInfo)
	mock.lockConfirmSignUpWithContext.Unlock()
	return mock.ConfirmSignUpWithContextFunc(ctx, input, opts...)
}

// ConfirmSignUpWithContextCalls gets all the calls that were made to ConfirmSignUpWithContext.
// Check the length with:
//
//	len(mockedAuthProvider.ConfirmSignUpWithContextCalls())
func (mock *AuthProviderMock) ConfirmSignUpWithContextCalls() []struct {
	Ctx   context.Context
	Input *cognitoidentityprovider.ConfirmSignUpInput
	Opts  []request.Option
} {
	var calls []struct {
		Ctx   context.Context
		Input *cognitoidentityprovider.ConfirmSignUpInput
		Opts  []request.Option
	}
	mock.lockConfirmSignUpWithContext.RLock()
	calls = mock.calls.ConfirmSignUpWithContext
	mock.lockConfirmSignUpWithContext.RUnlock()
	return calls
}

// SignUpWithContext calls SignUpWithContextFunc.
func (mock *AuthProviderMock) SignUpWithContext(ctx context.Context, input *cognitoidentityprovider.SignUpInput, opts ...request.Option) (*cognitoidentityprovider.SignUpOutput, error) {
	if mock.SignUpWithContextFunc == nil {
		panic("AuthProviderMock.SignUpWithContextFunc: method is nil but AuthProvider.SignUpWithContext was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *cognitoidentityprovider.SignUpInput
		Opts  []request.Option
	}{
		Ctx:   ctx,
		Input: input,
		Opts:  opts,
	}
	mock.lockSignUpWithContext.Lock()
	mock.calls.SignUpWithContext = append(mock.calls.SignUpWithContext, callInfo)
	mock.lockSignUpWithContext.Unlock()
	return mock.SignUpWithContextFunc(ctx, input, opts...)
}

// SignUpWithContextCalls gets all the calls that were made to SignUpWithContext.
// Check the length with:
//
//	len(mockedAuthProvider.SignUpWithContextCalls())
func (mock *AuthProviderMock) SignUpWithContextCalls() []struct {
	Ctx   context.Context
	Input *cognitoidentityprovider.SignUpInput
	Opts  []request.Option
} {
	var calls []struct {
		Ctx   context.Context
		Input *cognitoidentityprovider.SignUpInput
		Opts  []request.Option
	}
	mock.lockSignUpWithContext.RLock()
	calls = mock.calls.SignUpWithContext
	mock.lockSignUpWithContext.RUnlock()
	return calls
}
