name: Deploy Webapp

on:
  push:
    branches:
      - "main"
    paths:
    - "webapp/**"
    - ".github/workflows/deploy-webapp.yml"

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.4.6
  TF_WORKING_DIR: infra

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate .env.production
      run: |
        echo NEXT_PUBLIC_API_ROOT=${{ secrets.NEXT_PUBLIC_API_ROOT }} > webapp/.env.production

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # restapiコンテナが起動していることを確認する
    # タイムアウトは10分
    - name: Verify that the restapi is activated
      run: |
        timeout 600 bash <<'EOF'
        while : ; do
            status=$(aws ecs describe-services --region ap-northeast-1 --cluster tunetrail --services tunetrail-restapi --query 'services[0].status' --output text)
            if [[ "$status" = "ACTIVE" ]]; then
                break
            fi
            echo "Waiting for service to become ACTIVE..."
            sleep 10
        done
        EOF

    - name: Login to Amazon ECR (REST API)
      id: login-ecr-webapp
      uses: aws-actions/amazon-ecr-login@v1

    # イメージをビルドしてECRにプッシュする
    - name: Build, tag, and push webapp image to Amazon ECR
      id: build-image-webapp
      env:
        ECR_REGISTRY: ${{ steps.login-ecr-webapp.outputs.registry }}
        ECR_REPOSITORY: "tunetrail-webapp"
        IMAGE_TAG: ${{ github.sha }} # コミットハッシュをタグとして使用
      run: |
        cd webapp
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --target deploy .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # restapiのイメージタグを取得する
    - name: Get the latest restapi image tag
      id: get-restapi-tag
      run: |
        set -e
        result=$(aws ecs describe-task-definition --task-definition tunetrail-restapi --query 'taskDefinition.containerDefinitions[0].image' --output text || echo "error")
        if [ "$result" == "error" ]; then
          echo "Failed to describe the task definition."
          exit 1
        fi
        TAG=$(echo $result | cut -d ':' -f 2)
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    # migrationのイメージタグを取得する
    - name: Get the latest migration image tag
      id: get-migration-tag
      run: |
        set -e
        result=$(aws lambda get-function --function-name migration_lambda --query 'Code.ImageUri' --output text || echo "error")
        if [ "$result" == "error" ]; then
          echo "Failed to describe the lambda function."
          exit 1
        fi
        TAG=$(echo $result | cut -d ':' -f 2)
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # 先程pushしたイメージのタグをterraform applyに渡すことで、webappのタスク定義を更新する
    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        set -e
        terraform init
        terraform apply -auto-approve \
          -var "webapp_image_tag=${{ github.sha }}" \
          -var "restapi_image_tag=${{ steps.get-restapi-tag.outputs.tag }}" \
          -var "migration_image_tag=${{ steps.get-migration-tag.outputs.tag }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}"\
          -var "db_schema_bucket_name=${{ secrets.TUNETRAIL_S3_BUCKET }}" \
          -var "cognito_client_secret=${{ secrets.COGNITO_CLIENT_SECRET }}" \
          -var "cognito_admin_access_key=${{ secrets.COGNITO_ADMIN_ACCESS_KEY }}" \
          -var "cognito_admin_secret_key=${{ secrets.COGNITO_ADMIN_SECRET_ACCESS_KEY }}"
