name: Deploy REST API

on:
  push:
    branches:
      - "main"
    paths:
    - "restapi/**"
    - ".github/workflows/deploy-restapi.yml"

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.4.6
  TF_WORKING_DIR: infra

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR (REST API)
      id: login-ecr-restapi
      uses: aws-actions/amazon-ecr-login@v1

    # restapiのイメージをビルドしてECRにプッシュする
    - name: Build, tag, and push restapi image to Amazon ECR
      id: build-image-restapi
      env:
        ECR_REGISTRY: ${{ steps.login-ecr-restapi.outputs.registry }}
        ECR_REPOSITORY: "tunetrail-restapi"
        REST_API_IMAGE_TAG: ${{ github.sha }} # コミットハッシュをタグとして使用
      run: |
        cd restapi
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$REST_API_IMAGE_TAG --target deploy .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$REST_API_IMAGE_TAG

    # webappのイメージタグを取得する
    - name: Get the latest webapp image tag
      id: get-webapp-tag
      run: |
        set -e
        result=$(aws ecs describe-task-definition --task-definition tunetrail-webapp --query 'taskDefinition.containerDefinitions[0].image' --output text || echo "error")
        if [ "$result" == "error" ]; then
          echo "Failed to describe the task definition."
          exit 1
        fi
        TAG=$(echo $result | cut -d ':' -f 2)
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    # migrationのイメージタグを取得する
    - name: Get the latest migration image tag
      id: get-migration-tag
      run: |
        set -e
        result=$(aws lambda get-function --function-name migration_lambda --query 'Code.ImageUri' --output text || echo "error")
        if [ "$result" == "error" ]; then
          echo "Failed to describe the lambda function."
          exit 1
        fi
        TAG=$(echo $result | cut -d ':' -f 2)
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # 先程pushしたイメージのタグをterraform applyに渡すことで、restapiのタスク定義を更新する
    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        set -e
        terraform init
        terraform apply -auto-approve \
          -var "webapp_image_tag=${{ steps.get-webapp-tag.outputs.tag }}" \
          -var "restapi_image_tag=${{ github.sha }}" \
          -var "migration_image_tag=${{ steps.get-migration-tag.outputs.tag }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}"\
          -var "db_schema_bucket_name=${{ secrets.TUNETRAIL_S3_BUCKET }}" \
          -var "cognito_client_secret=${{ secrets.COGNITO_CLIENT_SECRET }}" \
          -var "cognito_admin_access_key=${{ secrets.COGNITO_ADMIN_ACCESS_KEY }}" \
          -var "cognito_admin_secret_key=${{ secrets.COGNITO_ADMIN_SECRET_ACCESS_KEY }}"
