name: golang-test

defaults:
  run:
    shell: bash
    working-directory: ./api

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "**.go"
      - ./../.github/workflows/golangtest.yml

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: tunetrail
          POSTGRES_PASSWORD: tunetrail
          POSTGRES_DB: tunetrail
        options: >-
          --health-cmd "pg_isready -U ${POSTGRES_USER}"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
    steps:
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
      - name: checkout code
        uses: actions/checkout@v3
      - name: migrate DB
        run: |
          go install github.com/k0kubun/sqldef/cmd/psqldef@latest
          psqldef --host=127.0.0.1 --port=5432 --user=tunetrail --password=tunetrail tunetrail < ./api/_tools/postgres/schema.sql
      - name: run tests
        run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0