name: next-test
on:
  pull_request:
    paths:
      - "frontend/**/*.ts"
      - "frontend/**/*.tsx"
      - ./.github/workflows/next-test.yml

jobs:
  nextci-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install dependencies
        run: npm ci
      - name: execute ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './src/**'
          fail_on_error: true
