name: Test for JavaScript and TypeScript
on:
  push:
    branches:
      - 'main'

  pull_request:
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - ./.github/workflows/test-js-and-ts.yml

defaults:
  run:
    shell: bash
    working-directory: ./webapp

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
